### PR TITLE
Added custom Jekyll theme

### PR DESCRIPTION
**Pull request by SteveReiter**
Adding a Jekyll custom theme to the site.

### CODE REVIEW

**Comment by MarkBennett** [comment]
Thanks for putting this together @stevereiter!

So I'm a bit confused about making this into a gem. Adding the `Gemfile` makes sense for managing dependencies. What's the advantage of making this a gem as well though? I'm probably just missing something though.

**Comment by SteveReiter** [comment]
Closed because we need some actual styling before we merge to master. We can continue work on the custom-theme branch.

**Comment by SteveReiter** [comment]
> Thanks for putting this together @SteveReiter!
> 
> So I'm a bit confused about making this into a gem. Adding the `Gemfile` makes sense for managing dependencies. What's the advantage of making this a gem as well though? I'm probably just missing something though.

I just copied instructions for how to get jekyll setup :P I think we have to make it into a gem for it to work with _config.yml, I'll try without building the gem and see if it still works.

**Comment by MarkBennett** [comment]
You should ping @ashia as she had two awesome bootstrap themes with basically everything we'd need for the homepage. On my phone and can't find them now but they were great and would probably work almost out of the box without too much effort.

**Comment by SteveReiter** [comment]
> You should ping @Ashia as she had two awesome bootstrap themes with basically everything we'd need for the homepage. On my phone and can't find them now but they were great and would probably work almost out of the box without too much effort.

This basically just let's us use markdown instead of html static pages.

**Comment by SteveReiter** [comment]
> Thanks for putting this together @SteveReiter!
> 
> So I'm a bit confused about making this into a gem. Adding the `Gemfile` makes sense for managing dependencies. What's the advantage of making this a gem as well though? I'm probably just missing something though.

Just tested it, looks like we don't need to bother building the gem.

The theme portion of this could be a different repository that builds a gem and uploads it somewheres, then the gemfile in this repo specifies that to load the theme.

**Pull request closed without merging**
